final stable pipeline fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,29 +1,16 @@
-name: GreenOps CI/CD Pipeline
+script: |
+  cd ~
+  cd GreenOps-Carbon-Aware-DevOps || { echo "Project folder not found"; exit 1; }
 
-on:
-  push:
-    branches:
-      - main
+  echo "Pulling latest code..."
+  git pull
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
+  echo "Stopping old app..."
+  pkill -f app.py || echo "No old process"
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+  echo "Starting app..."
+  cd demo_app || { echo "demo_app folder missing"; exit 1; }
 
-      - name: Deploy to EC2
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_KEY }}
-          script: |
-            cd ~
-            cd GreenOps-Carbon-Aware-DevOps || exit 1
-            git pull
-            pkill -f "app.py" || true
-            sleep 2
-            cd demo_app || exit 1
-            nohup python3 app.py > output.log 2>&1 &
+  nohup python3 app.py > output.log 2>&1 &
+
+  echo "Deployment completed successfully"
